### ISSUE TITLE
Not compatible with SQLAlchemy 1.4.2

### ISSUE THREAD

**Issue by vcalvert** [RazerM/sqlalchemy_aio#38]
This is the sort of error we see when attempting to use `sqlalchemy_aio` with `trio` and `sqlalchemy==1.4.2`:

```
File "/home/someuser/.local/lib/python3.8/site-packages/sqlalchemy_aio/strategy.py", line 1, in <module>
    from sqlalchemy.engine.strategies import DefaultEngineStrategy
ImportError: cannot import name 'DefaultEngineStrategy' from 'sqlalchemy.engine.strategies' (/home/someuser/.local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py)
```

**Comment by sycured** [comment]
@vcalvert  have you a good alternative?

**Comment by vcalvert** [comment]
@sycured, at this time, we don't have a tested alternative. At the moment, we've just pinned SQLAlchemy to <1.4.

We might use the built-in SQLAlchemy `AsyncEngine` via [`trio-asyncio`](https://pypi.org/project/trio-asyncio/), as that's relatively straightforward, but that's the only good option I'm aware of at the moment for use with `trio`. The `AsyncEngine` and other now-builtin parts provide a lot of the context managers, etc. so it may be a reasonable approach. Implementing a `trio`-compatible `AsyncEngine` would be more work, but wouldn't require the additional dependency (which we already need for some other things).

**Comment by sycured** [comment]
@vcalvert not really because I've an isu with metadata.reflect() which isn't working with new create_async_engine

Maybe I'll move another orm or language because I can't manage the database by the orm.

It's why I looked at sqlalchemy-aio but ok, I'll downgrade sqlalchemy and try it. Thanks

**Comment by prophile** [comment]
Would you mind reflecting the <1.4 requirement in the `install_requires` of `setup.py`?

**Comment by RazerM** [comment]
There are no plans to support SQLAlchemy 1.4, which adds proper async support.

**Comment by imperialguy** [comment]
I think [this](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html) is what you are referring to. But, I want to use it with [trio](https://github.com/python-trio/trio).

**Comment by imperialguy** [comment]
Any ideas on how to use it with trio?

**Comment by ghost** [comment]
Per the various above comments, the restriction on SQLAlchemy version has been added as of [release 0.17.0](https://github.com/RazerM/sqlalchemy_aio/releases/tag/0.17.0).

As I noted above, one way to use newer SQLAlchemy with [trio](https://github.com/python-trio/trio) is to use the [SQLAlchemy-provided asyncio code](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html) with [trio-asyncio](https://github.com/python-trio/trio-asyncio).

It's not terribly difficult, but it does bring in more dependences...

The other option is to essentially use a worker thread, i.e. 
``` python
result = await trio.to_thread.run_sync(db_operation_fn, params)
```
In one particular case I wrapped this sort of logic into a class with some error handling and other mechanisms to cache the result and prevent multiple invocations of the database query.

Closing due to the noted breakage not being possible anymore.

**Comment by Danangsatriani** [comment]
so whats the fix for this guys?
